<?php

    defined('BASEPATH') OR exit('No direct script access allowed');

    require APPPATH . '/libraries/REST_Controller.php';

    class Pacientes extends REST_Controller
    {
        function __construct()
        {
            // Construct the parent class
            parent::__construct();
        }

        public function index_get()
        {
            $pacientes = $this->pacientes_model->getPacientes();

            $id = $this->get('id');

            // If the id parameter doesn't exist return all the users

            if($id === null)
            {
                // Check if the users data store contains users (in case the database result returns NULL)
                if($pacientes)
                {
                    // Set the response and exit
                    $this->response($pacientes, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
                }
                else
                {
                    // Set the response and exit
                    $this->response([
                        'status' => false,
                        'message' => 'No users were found',
                    ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
                }
            }

            // Find and return a single record for a particular user.

            $id = (int)$id;

            // Validate the id.
            if($id <= 0)
            {
                // Invalid id, set the response and exit.
                $this->response(null, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
            }

            // Get the user from the array, using the id as key for retreival.
            // Usually a model is to be used for this.

            $paciente = null;

            if(!empty($pacientes))
            {
                foreach ($pacientes as $key => $value)
                {
                    if(isset($value['ID_USER']) && $value['ID_USER'] == $id)
                    {
                        $paciente = $value;
                        break;
                    }
                }
            }

            if(!empty($paciente))
            {
                $this->set_response($paciente, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }
            else
            {
                $this->set_response([
                    'status' => false,
                    'message' => 'User could not be found',
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }

        public function index_post()
        {
            $data = $this->post(null, true);
            if(!empty($data) || !is_null($data))
            {
                if($this->pacientes_model->postPaciente($data))
                {
                    // CREATED (201) being the HTTP response code
                    $this->set_response(['status' => true, 'data' => $data, 'message' => 'successfully source added'], REST_Controller::HTTP_CREATED);
                }
                else
                {
                    $this->response(['status' => false, 'message' => 'The username or email already exist'], REST_Controller::HTTP_OK);
                }
            }
            else
            {
                $this->response(null, REST_Controller::HTTP_BAD_REQUEST);
            }
        }

        public function index_put()
        {
            //$this->some_model->update_user(...);
            $message = [
                'id' => 100, // Automatically generated by the model
                'name' => $this->post('name'),
                'email' => $this->post('email'),
                'message' => 'Added a resource',
            ];

            $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }

        public function index_delete()
        {
            $id = (int)$_GET['id'];

            // Validate the id.
            if($id <= 0)
            {
                // Set the response and exit
                $this->response(null, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
            }

            $this->pacientes_model->deletePaciente($id);
            $message = [
                'id' => $id,
                'message' => 'Deleted the resource',
            ];

            $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
        }
    }
